Create Gyro assisted Autonomous Commands
FRC1076/2017-Competition pull request #20
Opened 2017-01-29 02:01 UTC by a2aaron

These commands utilize the gyro to drive straight and turn precisely.

2017-02-01 23:54 UTC, porglezomp requested changes
We'll experiment with some of these things tonight

2017-02-01 23:54 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/Robot.java
> +		ForwardWithGyro.SENSITIVITY = SmarterDashboard.getNumber("ForwardWithGyro Sensitivity", 1);
Should this be a static variable, or an instance variable?

2017-02-01 23:54 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/Robot.java
> +		ForwardWithGyro.SENSITIVITY = SmarterDashboard.getNumber("ForwardWithGyro Sensitivity", 1);
I can see static being fine since it's mostly about tweaking behavior for a given piece of hardware.

2017-02-01 23:54 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/commands/ForwardWithGyro.java
> +            rightSpeed = Math.signum(speed) * (Math.abs(speed) - Math.abs(gyroNorm));
Should these correct proportional to the speed instead of by subtracting a value?

2017-02-01 23:54 UTC, porglezomp commented on src/org/usfirst/frc/team1076/robot/commands/TurnWithGyro.java
> +    public boolean execute() {
This needs to ease out of turning

2017-02-11 02:28 UTC, a2aaron commented
Superceded by #34

2017-02-11 02:28 UTC, closed without merging